apiVersion: v1
kind: Secret
metadata:
  name: db-conn-secret
  namespace: todoapp
type: Opaque
stringData:
  NAME: todoapp
  USER: user
  PASSWORD: password
  HOST: mysql-0.mysql-headless.mysql.svc.cluster.local